name: Request review from translators

on:
  pull_request:
    types:
      - opened

env:
  PY_COLORS: 1
  UV_VERSION: 0.6.7

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: uv run .github/scripts/request_review.py

